filebeat.inputs:
  - type: filestream
    id: test-logs-simple
    enabled: true
    paths:
      - C:/Users/thuan/Documents/test.log
    fields:
      log_type: ssh
    fields_under_root: false

output.logstash:
  hosts: ["127.0.0.1:5044"]

